import { canonicalizeTeamName } from "../teamMetadata";

const TEAM_KEY_ALIASES = {
  uconn: "connecticut",
  unc: "north carolina",
  byu: "brigham young",
  vcu: "virginia commonwealth",
  tcu: "texas christian",
  smu: "southern methodist",
  usf: "south florida",
  "s florida": "south florida",
  "st mary s": "saint marys",
  "saint mary s": "saint marys",
  "st mary s ca": "saint marys",
  "st john s": "st johns",
  "saint john s": "st johns",
  "ohio st": "ohio state",
  "michigan st": "michigan state",
  "iowa st": "iowa state",
  "utah st": "utah state",
  "kennesaw st": "kennesaw state",
  "wright st": "wright state",
  "tennessee st": "tennessee state",
  "north dakota state": "north dakota st",
  "north dakota st": "north dakota st",
  "n dakota state": "north dakota st",
  "n dakota st": "north dakota st",
  ndsu: "north dakota st",
  "nc state": "north carolina state",
  "n c state": "north carolina state",
  "n c state wolfpack": "north carolina state",
  "miami fl": "miami",
  "miami florida": "miami",
  "miami ohio": "miami ohio",
  "miami oh": "miami ohio",
  "miami of ohio": "miami ohio",
  "queens n c": "queens nc",
  "queens nc": "queens nc",
  "queens royals": "queens nc",
  "queens n c royals": "queens nc",
  "queens nc royals": "queens nc",
  "queens university": "queens nc",
  "queens university royals": "queens nc",
  "queens university nc": "queens nc",
  "queens university n c": "queens nc",
  "queens charlotte": "queens nc",
  "queens charlotte royals": "queens nc",
  "queens university of charlotte": "queens nc",
  "queens university of charlotte royals": "queens nc",
  "kansas jayhawks": "kansas",
  "cal baptist lancers": "cal baptist",
  "california baptist lancers": "cal baptist",
  "prairie view a m panthers": "prairie view aandm",
  "prairie view a and m panthers": "prairie view aandm",
  "lehigh mountain hawks": "lehigh",
  "florida gators": "florida",
  "clemson tigers": "clemson",
  "iowa hawkeyes": "iowa",
  "st john s red storm": "st johns",
  "st johns red storm": "st johns",
  "northern iowa panthers": "northern iowa",
  "california baptist": "cal baptist",
  "cal baptist university": "cal baptist",
  "prairie view a m": "prairie view aandm",
  "prairie view a and m": "prairie view aandm",
  "texas a m": "texas am",
  "texas a and m": "texas am",
  "texas aandm": "texas am",
  "hawai i": "hawaii",
  "hawai i rainbow warriors": "hawaii",
};

function resolveLiveTeamKey(teamName) {
  const canonical = canonicalizeTeamName(teamName);
  return TEAM_KEY_ALIASES[canonical] || canonical;
}

function sameTeamKeys(teamAKey, teamBKey) {
  return resolveLiveTeamKey(teamAKey) === resolveLiveTeamKey(teamBKey);
}

export { resolveLiveTeamKey, sameTeamKeys };
